spring:
  application:
    name: tennis-court-manager
  data:
    mongodb:
      database: tennis-court-manager
      authentication-database: admin
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      host: ${MONGO_HOST}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${OAUTH2_CLIENT_ID}
            scope: openid
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: ${OAUTH2_ISSUER_URI}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}

keycloak:
  host: ${KEYCLOAK_HOST}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

sentry:
  dsn: https://081bffbf5f041cc606d659cd773b3f3a@o4509666161786880.ingest.de.sentry.io/4509666164998224
  send-default-pii: true
  environment: development
  logs.enabled: true
